name: Eatery Dev Server - CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup application properties file
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES_TEST }}" > ./src/main/resources/application-test.properties
          echo "${{ secrets.APPLICATION_PROPERTIES_DEV }}" > ./src/main/resources/application-dev.properties

      - name: Setup environment variables
        run: echo "${{ secrets.ENV_DEV }}" > ./.env

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
